### ISSUE TITLE
Add Credits section on README file

### ISSUE THREAD

**Issue by pedrohyvo** [ModusCreateOrg/modite-adventure#709]
@jaygarcia could we add a credits section with all contributors from Modus?

**Comment by jaygarcia** [comment]
Absolutely. :) Feel free to do so. Here's where we have credits in the code. :)

https://github.com/ModusCreateOrg/modite-adventure/blob/master/src/VictoryState/GVictoryCreditsProcess.h

**Comment by pedrohyvo** [comment]
@jaygarcia here's the example of contributors content:

<td align="center"><a href="https://moduscreate.com/"><img style="border-radius: 50%;" src="https://avatars.githubusercontent.com/u/180031?s=460&u=f5ad4d529a6c05b57429d68e85f27150afcf69a3&v=4" width="100px;" alt=""/><br /><sub><b>Jay Garcia</b></sub></a><br /><a href="https://rocketseat.com.br/" title="Game Design">👨‍🚀</a></td>

Let me know your thoughts and if it's good to redirect to the LinkedIn profile for each contributor or just redirects to Modus website?

**Comment by jaygarcia** [comment]
Let's roll with it! Love the direction!

**Comment by michaeltintiuc** [comment]
If it's not too hard we could perhaps do github /LinkedIn?

**Comment by pedrohyvo** [comment]
@michaeltintiuc good ideia, I'll link contributor's image profile to LI and the emoji below to github, makes sense?

**Comment by pedrohyvo** [comment]
Contributors section was added successfully! 🤩
